version: 0.2

phases:
  build:
    commands:
      - make build
  post_build:
    commands:
      - docker build . -t uggly
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - docker tag uggly:latest 514723210267.dkr.ecr.us-east-2.amazonaws.com/uggly:latest
      - docker push 514723210267.dkr.ecr.us-east-2.amazonaws.com/uggly:latest
